// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKP4TH1VIq9cb2vILghTne7m8tVLxB6JE',
    appId: '1:909148010311:web:2822e53203fbb015b4fe62',
    messagingSenderId: '909148010311',
    projectId: 'minnya-orange-chat',
    authDomain: 'minnya-orange-chat.firebaseapp.com',
    storageBucket: 'minnya-orange-chat.appspot.com',
    measurementId: 'G-SNFEZY8V5Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfpuk8xXRHtfvoOC779Mqofi50dsoebIM',
    appId: '1:909148010311:android:ba8a0142c1978d59b4fe62',
    messagingSenderId: '909148010311',
    projectId: 'minnya-orange-chat',
    storageBucket: 'minnya-orange-chat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCypJVzB965aolB-oYBzVQehK_V_1DHav8',
    appId: '1:909148010311:ios:1f8546adef308a86b4fe62',
    messagingSenderId: '909148010311',
    projectId: 'minnya-orange-chat',
    storageBucket: 'minnya-orange-chat.appspot.com',
    iosBundleId: 'com.minnya.orangeChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCypJVzB965aolB-oYBzVQehK_V_1DHav8',
    appId: '1:909148010311:ios:1f8546adef308a86b4fe62',
    messagingSenderId: '909148010311',
    projectId: 'minnya-orange-chat',
    storageBucket: 'minnya-orange-chat.appspot.com',
    iosBundleId: 'com.minnya.orangeChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKP4TH1VIq9cb2vILghTne7m8tVLxB6JE',
    appId: '1:909148010311:web:d2ede0bc1d6ff59cb4fe62',
    messagingSenderId: '909148010311',
    projectId: 'minnya-orange-chat',
    authDomain: 'minnya-orange-chat.firebaseapp.com',
    storageBucket: 'minnya-orange-chat.appspot.com',
    measurementId: 'G-R3TSDNPDVF',
  );

}